name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  actionlint:
    uses: ./.github/workflows/actionlint.yml
    permissions:
      contents: read
  codeql:
    uses: ./.github/workflows/codeql.yml
    permissions:
      actions: read
      contents: read
      pull-requests: read
      security-events: write
  pushover:
    name: pushover if failure
    if: github.ref_name == github.event.repository.default_branch && failure()
    needs: [actionlint, codeql]
    uses: ./.github/workflows/pushover.yml
    permissions: {}
    secrets:
      PUSHOVER_API_KEY: ${{ secrets.PUSHOVER_API_KEY }}
      PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
