name: Pushover

on:
  workflow_call:
    inputs:
      status:
        description: "ジョブの結果。success を渡すと成功通知になる"
        type: string
        default: "failure"
      title:
        description: "通知のタイトル。空なら Failed <repository>'s workflow (<workflow>)"
        type: string
        default: ""
      priority:
        description: "通知の優先度 (-2 〜 1)"
        type: number
        default: 1 # High
      sound:
        description: "通知音"
        type: string
        default: "falling"
    secrets:
      PUSHOVER_API_KEY:
        required: true
      PUSHOVER_USER_KEY:
        required: true

jobs:
  pushover:
    runs-on: ubuntu-latest
    permissions: {}
    timeout-minutes: 5
    steps:
      - name: pushover-actions
        # v1.2.0 のリリース待ち: https://github.com/umahmood/pushover-actions/issues/7
        uses: umahmood/pushover-actions@0582cb24dccd1fe77aeb35e6fb8027ddbca8af35 # main
        env:
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_API_KEY }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER_KEY }}
        with:
          status: ${{ inputs.status }}
          title: ${{ inputs.title != '' && inputs.title || format('Failed {0}''s workflow ({1})', github.repository, github.workflow) }}
          url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          priority: ${{ inputs.priority }}
          sound: ${{ inputs.sound }}
